services:
  - type: web
    name: rfnproject
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql

databases:
  - name: rfnproject-db
    databaseName: rfnproject
    user: root
    plan: free
